---
sidebar: sidebar 
permalink: detect-host.html 
keywords: detect, detect server instance, instance, detect a database host, instance 
summary: 在BlueXP  工作负载工厂中检测数据库的Microsoft SQL Server实例。 
---
= 检测Microsoft SQL Server实例
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在BlueXP  工作负载工厂中检测数据库的Microsoft SQL Server实例。

此任务用于检测_undetected instance_。

.关于此任务
如果AWS凭据在工作负载工厂关联、则数据库可以从SQL Server 2016开始自动发现具有以下AWS存储类型的Microsoft SQL Server：

* 适用于 ONTAP 的 FSX
* 弹性块存储(EBS)
* FSx for Windows File Server


在数据库中、发现的实例分类如下：

* _undetected instances _：工作负载工厂已自动发现的未检测实例。在以下情况下、不会检测到实例：
+
** Microsoft SQL Server身份验证失败。
** 适用于Microsoft SQL Server的FSx for ONTAP文件系统未在工作负载工厂向您的帐户注册。


* _Unmanaged Instances _：检测到不受工作负载工厂管理的实例
* _Managed Instances _：检测到由工作负载工厂管理的实例


在工作负载工厂中管理数据库的Microsoft SQL Server实例或主机实例的第一步是检测未检测到的数据库服务器实例。

.开始之前
检测未检测到的数据库服务器实例的要求如下：

* 您必须link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS帐户凭据"^]在工作负载工厂中检测数据库服务器实例。
* 实例的存储类型必须为以下类型之一：
+
** 适用于 ONTAP 的 FSX
** 弹性块存储(EBS)
** FSx for Windows File Server


* EC2实例必须具有允许使用SSM连接进行检测的角色/实例配置文件。
+
检测到Microsoft SQL实例后、不会修改现有环境。通过AWS Systems Manager会话管理器(SSM)进行检测。如果没有正确的IAM实例配置文件、检测将失败。link:https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-troubleshooting.html["了解有关SSM故障排除的更多信息"^](英文)



.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在数据库磁贴中，选择*转至数据库库存*。
. 在数据库中，选择*Inventory*选项卡。
. 单击下拉箭头、展开要检测的主机所在的行。
+
此时、主机将展开并显示主机实例。

. 单击要检测的实例的三个点菜单。
. 单击*detect*。
. 在*DETECT Instances*对话框中，提供Microsoft SQL Server用户名和密码或FSx for ONTAP用户名和密码。
+
工作负载工厂会验证您的Microsoft SQL凭据或FSx for ONTAP凭据。

+
如果其中任一凭据不可用、则Workload Factory会尝试在PowerShell中安装此 `aws.tools.SimpleSystemsManagement`模块。

. 单击*detect*。
+
此时将显示检测到的实例信息。

. 选择*是，通过工作负载工厂管理实例*或*否*。
. 单击 * 完成 * 。


.下一步行动
如果主机实例的存储类型为FSx for ONTAP，则可以 link:manage-server.html["通过工作负载工厂管理实例"]。
