---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory for Databases 是一种端到端数据库部署和维护服务，具有内置的优化最佳实践、自动精简克隆以及监控和解决功能。 
---
= 了解NetApp数据库工作负载工厂
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases 是一种端到端数据库部署和维护服务，具有内置的优化最佳实践、自动精简克隆以及监控和解决功能。



== 什么是NetApp Workload Factory for Databases？

NetApp Workload Factory for Databases 可发现、评估、规划、调配 Microsoft SQL Server、PostgreSQL 和 Oracle 数据并将其移动到 Amazon FSx for NetApp ONTAP（FSx for ONTAP）部署，以满足您的性能和成本期望，同时遵守行业最佳实践。NetApp Workload Factory for Databases 持续优化和管理 FSx for ONTAP 上的数据库。

有关 Workload Factory 的更多信息，请参阅link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["工作负载工厂概述"^]。



== 工作负载工厂为自管理数据库带来的优势

Workload Factory 为自管理数据库提供最佳实践和自动化。



=== 最佳实践

* 从AWS Cloud、Microsoft Windows和SQL Server以及NetApp ONTAP获得集成知识、用于在EC2实例上部署SQL Server。
* 总拥有成本优化部署。
* 遵循AWS、Microsoft和ONTAP最佳实践的端到端部署自动化。
* _快速创建_部署模式可帮助您避免手动配置的潜在陷阱。




=== 使用 Workload Factory Codebox 实现自动化

Workload Factory 通过 _Codebox_ 引入了内置自动化功能。  Codebox 具有以下自动化优势：

* *代码片段生成*：Workload Factory 在资源创建过程中生成基础设施即代码 (IaC) 片段，从而实现与现有编排工作流的无缝集成。
* *基础设施即代码副驾驶*：Codebox 是一个基础设施即代码 (IaC) 副驾驶，可帮助开发人员和 DevOps 生成代码来执行 Workload Factory 支持的任何操作。
* *代码查看器和自动化目录*：代码盒提供用于快速分析自动化的代码查看器和用于快速未来重复使用的自动化目录。




=== 数据库工作负载工厂功能

数据库工作负载工厂提供以下功能：

* *成本估算*：使用节约计算器评估潜在的成本节约，该计算器估算并详细说明了现有 Microsoft SQL Server 和 Oracle 部署使用 Elastic Block Store、FSx for Windows File Server 和本地部署与 FSx for ONTAP 相比的存储、计算、SQL 许可、快照和克隆逐项成本。
* *简单、快速的部署*：使用内置的 NetApp、Microsoft 和 Amazon 最佳实践来简化和简化主机、数据库和沙盒配置，从而消除 AWS 上 Microsoft SQL Server 和 PostgreSQL 实例的手动配置复杂性。
+
** 使用_快速_或_高级_创建模式从 Workload Factory 控制台部署，或通过 Codebox 创建、重用和自定义 AWS CloudFormation 模板，以便将来跨多个环境部署。
** 使用存储配置和沙盒克隆创建按需、隔离的数据库，这些数据库可用于测试、集成、诊断和培训，而不会影响生产数据。


* *精心设计的评估功能*：持续扫描您的 Microsoft SQL Server 和 Oracle 资产，获取全面的见解、机会和建议报告，以帮助您根据 AWS 最佳实践实现卓越运营、安全性、可靠性、性能效率和成本优化。
* *错误分析*：使用 AI 分析器分析和解决日志错误，以获取详细的错误消息、故障排除步骤和解决问题的建议。
* *集中管理*：从一个地方管理 FSx for ONTAP 上的 Microsoft SQL Server、Oracle 和 PostgreSQL 资源。在 Workload Factory 中，查看附加的基础架构、AWS 账户、凭据、连接的 FSx for ONTAP 文件系统、存储使用（包括 NFS 卷和 iSCSI LUN）、保护状态、性能、架构完善状态和错误分析。




== Amazon FSx for ONTAP为自助管理数据库带来的优势

* *持久性、可用性和可靠性*：FSx for ONTAP提供了多种功能来增强FSx for ONTAP上托管的自管理数据库的持久性和可用性、例如支持单可用性区域和多可用性区域部署的高可用性、应用程序感知型快照、使用复制改进的灾难恢复以及高效备份。
* *性能和可扩展性*：FSx for ONTAP可通过高吞吐量、低延迟、高速网络连接以及多个文件系统的可扩展性实现性能优化、从而扩展工作负载所需的聚合性能。
* *数据管理和效率*：FSx for ONTAP提供了多种可增强数据管理和效率的功能、例如节省空间的精简克隆、精简配置、数据压缩和重复数据删除以及将不常访问的数据分层到容量池。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["了解适用于 Workload Factory 的 FSx for ONTAP"^] 。



== 使用NetApp Workload Factory 的工具

您可以将NetApp Workload Factory 与以下工具一起使用：

* *Workload Factory 控制台*：Workload Factory 控制台提供您的应用程序和项目的可视化、整体视图。
* * NetApp控制台*： NetApp控制台提供混合界面体验，以便您可以将 Workload Factory 与其他NetApp数据服务一起使用。
* *问我*：使用问我 AI 助手来提问并了解有关 Workload Factory 的更多信息，而无需离开 Workload Factory 控制台。从 Workload Factory 帮助菜单访问“问我”。
* *CloudShell CLI*：Workload Factory 包含一个 CloudShell CLI，可通过基于浏览器的单个 CLI 跨账户管理和操作 AWS 和NetApp环境。从 Workload Factory 控制台顶部栏访问 CloudShell。
* *REST API*：使用 Workload Factory REST API 部署和管理您的 FSx for ONTAP文件系统和其他 AWS 资源。
* *CloudFormation*：使用 AWS CloudFormation 代码执行您在 Workload Factory 控制台中定义的操作，以从您的 AWS 账户中的 CloudFormation 堆栈对 AWS 和第三方资源进行建模、配置和管理。
* *Terraform NetApp Workload Factory 提供商*：使用 Terraform 构建和管理在 Workload Factory 控制台中生成的基础架构工作流。




== 支持的配置

您可以将 Workload Factory 与以下数据库引擎、版本、操作系统和部署模型一起使用，遵循 AWS、NetApp ONTAP、Microsoft SQL Server、Oracle 和 PostgreSQL 最佳实践。

[cols="1,1,1,1"]
|===
| 引擎 | 版本 | 操作系统 | 部署模型 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI，独立 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI，独立 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI，独立 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI，独立 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI，独立 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI，独立 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI，独立 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI，独立 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI，独立 


| Microsoft SQL Server | SQL 服务器 2017 | 任意 | FCI，独立 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | 任意 | FCI，独立 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | 任意 | Always On 可用性组 


| Oracle | 19c | RHEL、SuSe Linux | 独立（单/多租户） 


| Oracle | 21c | RHEL、SuSe Linux | 独立（单/多租户） 


| Oracle | 19c | RHEL、SuSe Linux | 独立（单/多租户） 


| Oracle | 21c | RHEL、SuSe Linux | 独立（单/多租户） 


| Oracle | 19c | RHEL、SuSe Linux | 独立于 ASM（单/多租户） 


| Oracle | 21c | RHEL、SuSe Linux | 独立于 ASM（单/多租户） 


| Oracle | 19c，21c | RHEL、SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | 亚马逊 Linux 2023 AMI | HA，独立实例 


| PostgreSQL | PostgreSQL 16 | 亚马逊 Linux 2023 AMI | HA，独立实例 
|===


== 集成AWS服务

数据库包括以下集成 AWS 服务：

* 云形成
* Simple Notification Service
* CloudWatch
* Systems Manager
* 机密管理器




== 区域

支持FSx for ONTAP的所有商业区域均支持数据库。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的 Amazon 地区。"^]

不支持以下AWS区域：

* 中国地区
* GovCloud (美国)地区
* 机密云
* 云的绝密




== 获取帮助

适用于NetApp ONTAP 的Amazon FSX是AWS第一方解决方案。如有与您的FSx for ONTAP文件系统、基础架构或使用此服务的任何解决方案相关的问题或技术支持问题、请使用AWS管理控制台中的支持中心创建AWS支持案例。选择 "FSX for ONTAP " 服务和相应的类别。提供创建 AWS 支持案例所需的其余信息。

有关 Workload Factory 或 Workload Factory 应用程序和服务的一般问题，请参阅link:get-help.html["获取有关NetApp Workload Factory for Databases 的帮助"]。
