---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: 数据库工作负载工厂定期分析 Microsoft SQL Server 和 Oracle 配置以确定是否存在任何问题。 
---
= Workload Factory 中的数据库环境配置分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
数据库工作负载工厂会定期分析数据库配置，以确定Amazon FSx for NetApp ONTAP存储上的 Microsoft SQL Server 和 Oracle 部署是否存在任何问题。当发现问题时，Workload Factory 会向您展示问题所在，并解释需要进行哪些更改以确保您的数据库配置达到最佳性能、成本效益并符合最佳实践。

主要功能包括：

* 每日配置分析
* 自动最佳实践验证
* 规模合适的建议
* 主动可观察性
* 从洞察力到行动
* AWS架构完善的Framework Advisor




== 工作原理

Workload Factory 每天分析在 Amazon FSx for NetApp ONTAP 文件系统部署上运行的工作负载。该分析提供了精心设计的状态、见解和建议。

每日分析完成后，配置在 Well-architected 仪表板中显示为"优化"或"未优化"。您可以找到总优化分数、按类别划分的配置问题以及配置问题和建议列表。您可以查看配置问题的建议。有些问题可以由 Workload Factory 自动修复，而其他问题则需要手动干预。在这种情况下，Workload Factory 会提供详细说明，以帮助您实施建议的更改。

您可以忽略不适用于您环境的配置分析。这样可以避免不必要的警报和不准确的优化结果。当您忽略特定配置分析时，Workload Factory 不将配置包含在总优化分数中。



== 为什么很重要

Workload Factory 通过将持续评估与建议见解和补救措施相结合，将最佳实践应用于大型存储、数据库和 VMware 环境。在 Workload Factory 控制台中应用的自动修复可减少人为错误，确保统一管理，并保持整个工作负载基础架构的性能和可靠性。



== 用于分析数据库环境的选项

Workload Factory 为分析数据库环境提供了以下选项：

* *一次性评估*：执行 link:optimize-configurations.html["一次性评估"] 以了解 Microsoft SQL Server 实例或 Oracle 数据库的良好架构状态，而无需存储凭据或注册资源。
* *持续监控*：注册资源以实现持续监控。Workload Factory 定期分析数据库环境，为优化配置提供持续建议，并自动修复问题。




== 分析要求

对于一次性评估，您只需为要分析的 Microsoft SQL Server 实例或 Oracle 数据库提供一次凭据。

要进行持续监控，需要在 AWS 帐户中注册资源、关联链接并授予权限。

* link:register-instance.html["注册您的资源"] 并确保它们处于联机状态。
* 关联链接。链接连接让 Workload Factory 能够分析所有数据库部署配置，例如存储布局和弹性。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建和关联新链接"]。

* 在您的 AWS 账户中授予查看、规划和分析权限。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["了解如何向 AWS 帐户授予权限"^]





== 数据库工作负载的最佳实践和建议

Workload Factory 提供了一套最佳实践和建议，用于运行精心设计的数据库工作负载。精心设计的分析评估与存储规模、存储布局、存储配置、计算、应用程序（SQL Server）和弹性相关的 Microsoft SQL Server 和 Oracle 数据库配置和设置。



=== Microsoft SQL Server



==== 存储规模调整

* *存储层*
+
使用 FSx for ONTAP 卷的主 SSD 层来确保最佳性能。容量池层可能会降低性能并增加延迟。主 SSD 层专为高性能工作负载而设计，而容量池层则针对成本效益进行了优化，可能无法满足 SQL Server 工作负载的性能要求。

* *文件系统余量*
+
将文件系统容量保持在总卷大小以上。空间太小会导致性能问题；浪费太多存储空间并增加成本。

* *日志驱动器大小*
+
适当调整 SQL Server 日志驱动器的大小并进行监控，以防止事务回滚、数据库不可用、数据损坏以及由完整日志驱动器导致的性能问题。

* *TempDB 驱动器大小*
+
适当调整 TempDB 大小并进行监控，以保持最佳性能和系统稳定性。TempDB 空间不足会导致查询速度减慢、应用程序超时和系统崩溃。





==== 存储布局

* *数据文件 (.mdf) 放置*和*日志文件 (.ldf) 放置*
+
将数据和日志文件放在单独的驱动器上，以提高性能并实现独立的备份和还原操作。

* *TempDB 放置*
+
将 TempDB 放在专用驱动器上，以避免 I/O 争用并提高 SQL Server 性能和稳定性。否则，您可能会遇到 I/O 瓶颈、查询速度变慢和系统不稳定。





==== 存储配置

* *ONTAP 配置*
+
为 FSx for ONTAP 卷启用精简配置、自动大小和空间管理，以优化存储效率和成本效益。配置分层策略以将较旧的快照移动到容量层，同时保持活动数据的高性能。对于 LUN，请确保操作系统类型与操作系统分区方案匹配，以实现正确的 I/O 对齐，启用空间保留以防止写入失败，并启用空间分配以允许在存储已满时自动回收空间并发出主机通知。

* *操作系统*
+
使用适当的超时设置启用和配置 Microsoft 多路径 I/O (MPIO)，以确保 EC2 上使用 FSx for ONTAP 的 SQL Server 数据库的高可用性和数据访问一致性。MPIO 为故障转移期间的增强弹性和性能提供了冗余路径。适当配置 NTFS 分配单元大小，以实现最佳磁盘利用率和性能。





==== 计算

* *计算资源优化*
+
根据工作负载需求调整 SQL Server EC2 实例的大小，以平衡性能和成本效益。如果当前实例配置不足，升级可以增强 CPU、内存和 I/O 容量。如果过度配置，降级可以在降低成本的同时保持性能。

* *操作系统补丁*
+
应用最新的操作系统补丁，增强安全性和系统可靠性。

* *网络适配器设置*
+
配置接收端扩展 (RSS) ，以跨多个处理器分布网络处理并提高网络性能。在应用于生产之前测试设置。

* *MTU 对齐*
+
将 EC2 实例最大传输单元 (MTU) 设置与 FSx for ONTAP 对齐，以防止网络碎片化并优化 SQL Server 性能。修复 MTU 未对齐问题可确保所有节点和网络路径之间的 MTU 配置一致。





==== 应用程序 (SQL Server)

* *许可证*
+
SQL Server 许可证评估和建议在主机级别提供。当 Workload Factory 检测到您的数据库基础架构未使用您支付的任何商业软件许可证功能时，它会将许可证视为"未优化"。未优化的许可证可能会导致不必要的成本。检查您的 SQL Server 许可证使用情况，以确保您正在使用您支付的所有功能。

* *Microsoft SQL Server 修补程序*
+
应用最新的 SQL Server 修补程序以增强安全性、防范漏洞并提高系统可靠性。

* *MAXDOP*
+
配置 MAXDOP 以优化查询性能。值 4、8 或 16 通常效果很好。测试您的工作负载并监控并行度等待类型，例如 CXPACKET。





==== 故障恢复能力

* *计划本地快照*
+
安排定期快照以进行时间点备份，并从意外删除、数据损坏和其他问题中快速恢复。

* *备份配置*
+
配置 FSx for ONTAP 备份或 AWS Backup 以满足数据保留和合规性要求。避免重复备份。

* *跨区域复制*
+
启用跨区域复制 (CRR) 以提高数据可用性和灾难恢复。使用 CRR 来防止区域中断并确保业务连续性。

* *Microsoft SQL Server 高可用性*
+
通过检查所有群集节点都可以访问所有共享存储，跨节点的驱动器号相同以防止故障转移过程中的冲突，为群集运行状况设置仲裁，为云环境设置心跳阈值以及为自动启动和故障转移设置 SQL Server 服务，确保为 SQL Server 设置了高可用性。

* *克隆清理*
+
定期审查和删除过时的克隆，以降低存储成本。旧的和未使用的克隆会导致高成本。





=== Oracle



==== 存储规模调整

* *文件系统余量*
+
保持足够的文件系统容量，以优化存储性能并防止性能下降。充足的空间可实现高效的存储管理，并支持数据库增长。

* *交换空间*
+
根据 RAM 数量设置交换空间，以便系统可以处理内存压力并避免减速或崩溃。





==== 存储布局

* *Oracle 二进制放置*
+
将 Oracle 二进制文件放在专用卷上，通过减少 I/O 竞争来确保最佳性能和稳定性。这种分离简化了软件更新，并将意外修改或损坏的风险降至最低。

* *数据文件放置*
+
将数据文件放置在专用卷上或与控制文件一起，以隔离随机 I/O 并提高性能。这种分离可实现自定义快照配置、分层策略和效率机制，以优化性能和成本。

* *控制文件放置*
+
将控制文件的副本存储在不同的卷或磁盘上，以避免单点故障并增加冗余。将控制文件放置在专用卷上，或与重做日志或数据文件共享，但由于性能要求，请勿将其放置在分层到对象存储的卷上。

* *重做日志放置*
+
将重做日志放在专用卷上，或与临时或控制文件适当共享，以隔离高写入 I/O 操作并提高性能。将重做日志的每个副本存储在单独的卷上，以实现冗余。请勿将重做日志放置在卷快照或分层到对象存储的卷上，因为它们会经常更新。

* *临时放置*
+
将临时文件放置在专用卷上，或与重做或控制文件适当共享，以隔离高写入 I/O 操作并提高性能。每个多路复用的临时副本应驻留在单独的卷上，以实现冗余。由于其频繁更新模式，不应将临时文件放置在卷快照或分层到对象存储的卷上。

* *归档放置*
+
将存档日志放置在专用卷上，以通过防止高 I/O 要求干扰其他数据库操作来增强性能和恢复过程。

* *仅限 ASM 配置：ASM 数据磁盘组 LUN、ASM 日志磁盘组 LUN 和 ASM 存档磁盘组 LUN*
+
将 LUN 分布在 Automatic Storage Management (ASM) 数据、重做日志和归档日志磁盘组中，以实现最佳性能和冗余。





==== 存储配置

* *ONTAP*
+
通过为卷启用精简配置、自动调整大小和空间管理，优化 FSx for ONTAP 配置以支持 Oracle 数据库。配置适当的快照策略和分层策略，以平衡性能和成本。对于 LUN，确保正确的操作系统类型对齐、空间保留和空间分配设置，以防止写入失败并启用自动空间回收。

* *操作系统*
+
配置操作系统设置以获得最佳 Oracle 数据库性能，包括调整数据库工作负载的内核参数以及为网络文件系统访问适当配置 NFS 或 dNFS 设置。





==== 计算

* *操作系统补丁*
+
定期应用操作系统修补程序，以确保 Oracle 数据库环境的安全性、稳定性和性能改进。





==== 应用程序

* *Oracle 关键补丁更新*
+
应用最新的 Oracle Critical Patch Updates 来解决安全漏洞并维护数据库环境的完整性。定期审查和应用补丁，以防范潜在威胁，并确保符合安全最佳实践。





==== 故障恢复能力

* *跨区域复制 (CRR)*
+
启用跨区域复制 (CRR) 以增强 Oracle 数据库的数据可用性和灾难恢复能力。CRR 通过跨地理位置分散的位置复制数据，帮助防止区域中断并确保业务连续性。

* *应用程序一致性快照*
+
使用与 NetApp SnapCenter 应用程序一致的快照，在特定时刻为卷数据拍摄准确、可靠的快照。这可确保您的应用程序顺利运行和数据安全。SnapCenter 使备份更轻松，并帮助您快速、正确地还原数据，从而减少停机时间并保护您最重要的工作负载。

* *备份配置*
+
配置 FSx for ONTAP 备份或 AWS Backup 以满足数据保留和合规性要求。避免重复备份。

* *克隆清理*
+
定期审查和删除过时的克隆，以降低存储成本。旧的和未使用的克隆会导致高成本。



.下一步行动
link:optimize-configurations.html["实施结构良好的数据库配置"]
