---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: 数据库工作负载工厂定期分析 Microsoft SQL Server 和 Oracle 配置以确定是否存在任何问题。 
---
= Workload Factory 中的数据库环境配置分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
数据库工作负载工厂会定期分析数据库配置，以确定Amazon FSx for NetApp ONTAP存储上的 Microsoft SQL Server 和 Oracle 部署是否存在任何问题。当发现问题时，Workload Factory 会向您展示问题所在，并解释需要进行哪些更改以确保您的数据库配置达到最佳性能、成本效益并符合最佳实践。

主要功能包括：

* 每日配置分析
* 自动最佳实践验证
* 规模合适的建议
* 主动可观察性
* 从洞察力到行动
* AWS架构完善的Framework Advisor




== 架构良好的状态

在文件系统级别的 Workload Factory 控制台中，列出了所有 FSx for ONTAP文件系统的良好架构状态。架构良好的状态分为“问题”、“未分析”或“架构良好”。选择良好架构状态会将您重定向到文件系统内的良好架构状态选项卡，您可以在其中找到良好架构分数、配置类别以及文件系统的所有配置。



== 精心设计的得分

得分包括当前分析的所有配置、并以百分比形式显示。25%的分数表示25%的文件系统配置设计良好。



== 配置类别

文件系统配置会根据AWS精心设计的框架的以下五大支柱按类别进行组织。

* _Reliability _：确保工作负载正确一致地执行其预期功能、即使发生中断也是如此。例如、FSx for ONTAP备份就是一个配置示例。
* _Security_：强调通过风险评估和缓解策略保护数据、系统和资产。
* _卓越运营_：专注于提供最优架构和业务价值。
* _成本优化_：旨在提供业务价值、同时最大程度地降低成本。
* _Performance效率_：侧重于高效利用资源来满足系统要求、并在需求变化时保持最佳性能。




== 分析范围

优化范围因评估的组件而异。例如、存储优化在SQL实例级别进行、而计算优化在主机级别进行。



== 分析要求

为了进行完整的数据库环境分析，资源必须注册并在线。

link:register-instance.html["了解如何注册资源。"]

.下一步行动
link:optimize-configurations.html["实施结构良好的数据库配置"]
