---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 适用于数据库的BlueXP  工作负载工厂会扫描Microsoft SQL Server配置、提供洞察力和建议、帮助您实现卓越运营。 
---
= 优化Microsoft SQL Server部署的配置
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
适用于数据库的BlueXP  工作负载工厂会持续扫描和评估在Amazon FSx for NetApp ONTAP上运行的Microsoft SQL Server部署配置。此功能可提供洞察力和建议、并可选择自动优化未经优化的配置、以便数据库工作负载实现卓越运营。

.关于此任务
对于采用工作负载工厂管理的FSx for ONTAP存储的Microsoft SQL Server实例、此评估每天自动持续运行一次。只有在部署后或管理实例后运行每日计划作业时、优化信息板才会显示评估报告。

工作负载工厂根据FSx for ONTAP存储的最佳实践提供了详细的配置优化建议。您可以查看这些建议并选择优化未优化的配置。

扫描的内容:: 工作负载工厂会评估Microsoft SQL Server实例的以下配置的优化状态：
+
--
* 存储规模估算：包括存储层、文件系统余量、日志驱动器大小和TempDB驱动器大小
* 存储布局：包括用户数据文件放置、日志文件放置和TempDB放置
* 存储配置：包括容量管理、精简配置、分层策略、快照和多路径I/O状态、策略和会话等
* 计算：包括规模估算、操作系统修补程序和网络适配器设置、例如接收端扩展(RSS)和TCP负载分流
* 应用程序：包括Microsoft SQL Server许可证、Microsoft SQL Server修补程序和MAXDOP设置
* 故障恢复能力：包括本地快照、FSx for ONTAP备份和跨区域复制(CRR)
* clones：可用于刷新和删除超过60天的克隆(沙盒)


--


.开始之前
* 您必须具有具有读取或自动执行权限的凭据。
* 要评估Microsoft SQL Server实例的存储、该实例必须由工作负载工厂进行管理、并且存储类型必须为FSx for ONTAP。
* 在选择优化设置或配置之前、请确保仔细查看每个建议。对于RSS和MAXDOP设置、我们建议您在更改生产环境之前测试建议的设置以确定性能改进。



NOTE: 优化过程可能会导致实例停机或服务中断。在选择优化配置之前、请务必查看优化摘要和操作项。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在数据库磁贴中，选择*转至数据库清单*。
. 在*Inventory*选项卡中，选择*Instances *选项卡。
. 选择要优化的实例的三点菜单，然后选择*Optimize*。
. 在SQL Server实例的优化实例页面上、查看评估结果。
+
您可以按类别、子类别、状态、严重性和标记进行筛选。

+
您也可以通过选择*导出PDF*来下载评估结果报告。

. 选择下拉箭头可查看任何配置的建议。请务必仔细阅读此建议。
+
此建议说明了未优化配置的最佳实践和潜在陷阱。

. 选择此选项可*优化*未优化的配置。
+
*全选*为默认设置，但您可以选择要优化的特定资源。

+
.. 对于除克隆清理之外的所有配置、请查看优化对话框中的优化详细信息、了解选择优化时会发生什么情况。某些优化操作可能会导致实例停机或服务中断。
.. 对于克隆清理、请选择要刷新或删除的克隆数据库(沙盒)。
+
*** 刷新克隆会将其与其源数据库同步。刷新仅适用于在工作负载出厂时创建的克隆。
*** 删除克隆将永久删除该克隆、释放存储空间并降低成本。您可以删除在工作负载出厂时和出厂时创建的克隆。




. 选择*继续*以优化配置。


.结果
此时将启动优化过程。选择*作业监控*选项卡以查看操作状态。
