---
settings:
  name: Database workloads
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: 数据库工作负载文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 已知限制
      url: "/known-limitations.html"
  - title: 开始使用
    entries:
    - title: 了解数据库工作负载工厂
      url: "/learn-databases.html"
    - title: 快速入门
      url: "/quick-start-databases.html"
  - title: 使用数据库工作负载
    entries:
    - title: 了解节省量
      url: "/explore-savings.html"
    - title: 创建新的数据库服务器
      entries:
      - title: 创建Microsoft SQL Server
        url: "/create-database-server.html"
      - title: 创建PostgreSQL服务器
        url: "/create-postgresql-server.html"
    - title: 检测数据库服务器
      url: "/detect-host.html"
    - title: 创建数据库
      url: "/create-database.html"
    - title: 使用CodeBox实现自动化
      url: "/automate-codebox.html"
  - title: 管理和监控
    entries:
    - title: 管理Microsoft SQL Server
      url: "/manage-server.html"
    - title: 管理克隆
      entries:
      - title: 创建沙盒克隆
        url: "/create-sandbox-clone.html"
      - title: 检查沙盒克隆的完整性
        url: "/check-clone-integrity.html"
      - title: 还原沙盒克隆
        url: "/revert-clone.html"
      - title: 刷新沙盒克隆
        url: "/refresh-clone.html"
      - title: 连接到CI/CD管道
        url: "/connect-clone-cicd.html"
      - title: 查看克隆连接信息
        url: "/view-clone-connection.html"
      - title: 拆分沙盒克隆
        url: "/split-clone.html"
      - title: 删除沙盒克隆
        url: "/delete-clone.html"
    - title: 监控数据库
      url: "/monitor-databases.html"
    - title: 优化SQL Server
      entries:
      - title: 持续优化概述
        url: optimize-overview.html
      - title: 优化配置
        url: optimize-configurations.html
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/support-registration.html"
    - title: 获取帮助
      url: "/get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory for AWS
  repo: workload-family
