---
sidebar: sidebar 
permalink: register-instance.html 
keywords: manage, register, Microsoft SQL Server instance, Oracle database, manage database, manage instance 
summary: 注册资源，以便您可以监控NetApp Workload Factory for Databases 中的资源状态、资源利用率、保护和存储性能。 
---
= 在NetApp Workload Factory for Databases 中注册资源
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
注册 Microsoft SQL Server 实例和 Oracle 数据库，以便您可以在NetApp Workload Factory for Databases 中监控实例和数据库状态、资源利用率、保护和存储性能。

仅在 FSx for ONTAP文件系统存储上运行的数据库引擎才可以注册。



== 关于任务

注册实例（SQL Server）或数据库（Oracle）包括两个步骤 - 身份验证和准备。准备工作包括确保所有 AWS、 NetApp和 PowerShell 模块都安装在实例上。

您可以使用 SQL Server 凭据或 Windows 凭据进行身份验证。


NOTE: Workload Factory 仅支持 Microsoft SQL Server 实例和 Oracle 数据库的注册和管理。根据您在 Workload Factory 中选择的 AWS 帐户凭证，PostgreSQL 主机可能会出现在清单中。目前，Workload Factory 仅支持在 Amazon Linux 操作系统上运行的未注册的 PostgreSQL 实例。



== 开始之前

注册实例之前请考虑以下事项：

实例或数据库的主机必须出现在清单中。要使主机出现在清单中，link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["您必须添加 AWS 账户凭证和“只读”或“读/写”模式权限"^] 。



=== 在私有网络中注册实例

要在没有外部连接的私有网络中注册实例（SQL Server）或数据库（Oracle），需要在 VPC 中提供以下终端节点，并与 SQL Server 所在的子网关联。确保接口端点允许附加的安全组中的端口 443。

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`
+
如果您使用代理服务器进行EC2实例中的所有出站连接、则必须允许访问以下域、才能使管理操作正常工作：

* ``.microsoft.com``（SQL 服务器）
* ``.powershellgallery.com``（SQL 服务器）
* ``.aws.amazon.com``
* ``.amazonaws.com``




== 注册 SQL Server 实例

注册实例包括实例认证和准备。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在数据库磁贴中，选择*转至数据库清单*。
. 从数据库菜单中，选择*Inventory*。
. 在清单中，选择 *Microsoft SQL Server* 作为引擎类型。
. 选择“*实例*”选项卡。
. 选择注册单个实例或多个实例。
+
.. 单实例注册：导航到要管理的实例并选择*注册实例*。
.. 多实例注册：选择*注册多个实例*按钮。
+
注册多个实例有两种方式。两种情况下，实例必须具有相同的身份验证状态（未身份验证或已身份验证）。

+
*** 未经身份验证的实例：选择多个未经身份验证的实例进行注册。这些实例必须共享相同的身份验证凭据和 FSx for ONTAP 凭据。选择“应用”，然后选择“下一步”。
*** 已认证实例：选择多个已认证实例进行注册，然后选择*下一步*。




. 在“注册实例”页面的第 2 步中，选择实例身份验证模式，输入以下详细信息，然后选择“下一步”。如果实例已通过身份验证，请选择“下一步”。
+
** *SQL Server 身份验证*：输入 SQL Server 用户名和密码，以及 FSx for ONTAP 文件系统用户名和密码。
** *Windows 身份验证*：输入 Windows 用户名和密码，以及 FSx for ONTAP 文件系统用户名和密码。


. 在步骤 3 中，通过确保实例满足所需的先决条件来准备实例。如果所有必需模块均已安装且先决条件均已满足，请选择“下一步”以注册实例。如果您需要采取行动，请按照以下步骤操作。
+
.. 如果缺失，请选择工作负载工厂来*安装缺失的 AWS 和 NetApp PowerShell 模块*。
.. 如果缺失，请选择“工作负载工厂”来“安装缺失的 PowerShell 7”。安装缺失的 PowerShell 模块 7 需要重启系统。
.. 查看以下功能的先决条件列表。确保您满足注册实例的每个功能的所有先决条件。
+
*** *审查精心设计的问题和建议*
*** *修复架构问题*
*** 创建数据库
*** 创建数据库副本（沙盒）
+
完成先决条件包括更新您的 AWS IAM 策略权限、EC2 IAM 实例配置文件权限、SQL Server 权限和 PowerShell 模块。



.. 当先决条件完成并且检查*准备就绪*时，您可以选择*注册*该实例。




.结果
实例注册启动。选择“作业监控”选项卡来跟踪进度。



== 注册 Oracle 数据库

注册数据库包括实例认证和准备。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在数据库磁贴中，选择*转至数据库清单*。
. 从数据库菜单中，选择*Inventory*。
. 在清单中，选择 *Oracle* 作为数据库引擎。
. 选择“*数据库*”选项卡。
. 选择注册单个数据库或多个数据库。
+
.. 单个数据库注册：导航到要管理的数据库并选择*注册数据库*。
.. 多数据库注册：选择*注册多个数据库*按钮。
+
有两个选项可用于注册多个数据库。在这两种情况下，数据库必须共享相同的身份验证状态（未经身份验证或已身份验证）。

+
*** 未经身份验证的数据库：选择多个未经身份验证的数据库进行注册。这些数据库必须共享相同的身份验证凭据和 FSx for ONTAP凭据。选择“*应用*”，然后选择“*下一步*”。
*** 已验证的数据库：选择多个已验证的数据库进行注册，然后选择*下一步*。




. 在注册数据库页面的第 2 步中，选择数据库身份验证模式，输入以下详细信息，然后选择*下一步*。如果数据库已经过身份验证，请选择“下一步”。
+
** *Oracle 用户身份验证*：输入 Oracle 用户名和密码，以及 FSx for ONTAP文件系统用户名和密码。
** *Oracle ASM 用户身份验证*：可选。如果 Oracle 数据库使用自动存储管理 (ASM)，请输入 Oracle ASM（网格）用户名和密码。


. 在步骤 3 中，准备数据库，确保数据库满足所需的先决条件。如果安装了所有必需的模块并且满足先决条件，请选择“*下一步*”来注册数据库。如果您需要采取行动，请按照以下步骤操作。
+
.. 查看以下功能的先决条件列表。必须满足单个功能的所有先决条件才能注册数据库。
+
*** *审查精心设计的问题和建议*


.. 完成以下先决条件：
+
*** *AWS IAM 策略权限*：在 AWS 控制台中复制和更新 AWS 权限。
*** *EC2 IAM 实例配置文件权限*：在 AWS 控制台中复制并更新 Amazon EC2 实例上的 EC2 IAM 实例配置文件权限。
*** *部署模块*：如果需要，选择安装依赖模块，包括 AWS 命令行界面 (AWS CLI)、jq（命令行 JSON 处理器）和 Python 3.12（如果尚未安装 3.6 或更高版本）。工作负载工厂会在注册过程中自动安装这些模块。
*** *Oracle 用户权限*：如果需要，更新 Oracle 用户的权限。


.. 当先决条件完成并且检查*准备就绪*时，您可以选择*注册*数据库。




.结果
数据库注册启动。选择“作业监控”选项卡来跟踪进度。

.下一步行动
资源注册后，您可以执行以下操作。

* 从清单中查看数据库
* link:create-database.html["创建数据库"]
* link:create-sandbox-clone.html["创建数据库克隆（沙盒）"]
* link:optimize-configurations.html["实施结构良好的数据库配置"]

